<?php

define('TILE_TYPE_LAND', 0);
define('TILE_TYPE_SEA',  1);

class Tile
{
	//////////////////////////
	//  Logical Attributes  //
	//////////////////////////
	
	/** Array of neighbouring tiles
	 * 
	 * @var array
	 */	
	private $neighbours;
	
	/** Production poitns generated by this tile
	 * 
	 * @var int
	 */
	private $production;
	
	/** Current controller of this tile
	 * 
	 * @var Nation
	 */
	private $controller;
	
	/** Type of th tile (sea or land)
	 * 
	 * @var TILE_TYPE_LAND or TILE_TYPE_SEA
	 */
	private $type;
	
	///////////////////////////
	// Structural Attributes //
	///////////////////////////
	/** The tile polygon's center vertex
	 * 
	 * @var array of int
	 */
	private $center;
	
	/** The tile polygon's vertices
	 * 
	 * @var array of array of int
	 */
	private $vertices;
	
	/** The position of text, units, etc ??? NOT SURE !!!
	 * 
	 * @var array of array of int
	 */
	private $places;
	
	///////////////////////////
	// Methods and Functions //
	///////////////////////////
	
	/** Calculates the path to another tile using A*
	 * 
	 * @param Tile $other
	 * @returns array of Tile
	 */
	public function &pathTo(Tile &$other)
	{
		// do A*
		return $other;
	}
}

?>