UPDATE tiles SET tile_center_x = 602, tile_center_y = 246 WHERE tile_name LIKE 'SZ 3 Labrador Sea';
UPDATE tiles SET tile_center_x = 2752, tile_center_y = 993 WHERE tile_name LIKE 'Yunnan';
UPDATE tiles SET tile_center_x = 1424, tile_center_y = 627 WHERE tile_name LIKE 'France';
UPDATE tiles SET tile_center_x = 1994, tile_center_y = 2104 WHERE tile_name LIKE 'SZ 68 South Indian';
UPDATE tiles SET tile_center_x = 4755, tile_center_y = 849 WHERE tile_name LIKE 'Southwestern United States';
UPDATE tiles SET tile_center_x = 2433, tile_center_y = 987 WHERE tile_name LIKE 'Delhi';
UPDATE tiles SET tile_center_x = 2767, tile_center_y = 1377 WHERE tile_name LIKE 'Sumatra';
UPDATE tiles SET tile_center_x = 3195, tile_center_y = 786 WHERE tile_name LIKE 'SZ 74 Sea of Japan';
UPDATE tiles SET tile_center_x = 1972, tile_center_y = 366 WHERE tile_name LIKE 'Northern Russia';
UPDATE tiles SET tile_center_x = 4198, tile_center_y = 194 WHERE tile_name LIKE 'Alaska';
UPDATE tiles SET tile_center_x = 3091, tile_center_y = 758 WHERE tile_name LIKE 'Chosen';
UPDATE tiles SET tile_center_x = 889, tile_center_y = 817 WHERE tile_name LIKE 'SZ 20 Atlantic';
UPDATE tiles SET tile_center_x = 1236, tile_center_y = 837 WHERE tile_name LIKE 'SZ 22 East Atlantic';
UPDATE tiles SET tile_center_x = 539, tile_center_y = 642 WHERE tile_name LIKE 'SZ 13 Gulf of St Lawrence';
UPDATE tiles SET tile_center_x = 2062, tile_center_y = 251 WHERE tile_name LIKE 'Archangel\'sk';
UPDATE tiles SET tile_center_x = 2914, tile_center_y = 519 WHERE tile_name LIKE 'Buryatia';
UPDATE tiles SET tile_center_x = 1643, tile_center_y = 863 WHERE tile_name LIKE 'SZ 26 Central Mediterranean';
UPDATE tiles SET tile_center_x = 3308, tile_center_y = 939 WHERE tile_name LIKE 'SZ 86 West Pacific';
UPDATE tiles SET tile_center_x = 638, tile_center_y = 1213 WHERE tile_name LIKE 'SZ 38 Mid Atlantic';
UPDATE tiles SET tile_center_x = 1678, tile_center_y = 393 WHERE tile_name LIKE 'SZ 12 East Baltic Sea';
UPDATE tiles SET tile_center_x = 80, tile_center_y = 1233 WHERE tile_name LIKE 'SZ 36 East Pacific';
UPDATE tiles SET tile_center_x = 49, tile_center_y = 452 WHERE tile_name LIKE 'Central Canada';
UPDATE tiles SET tile_center_x = 1473, tile_center_y = 1468 WHERE tile_name LIKE 'SZ 45 Mid Atlantic';
UPDATE tiles SET tile_center_x = 1416, tile_center_y = 282 WHERE tile_name LIKE 'SZ 10 North Sea';
UPDATE tiles SET tile_center_x = 1342, tile_center_y = 447 WHERE tile_name LIKE 'Scotland';
UPDATE tiles SET tile_center_x = 3320, tile_center_y = 332 WHERE tile_name LIKE 'Okhotsk';
UPDATE tiles SET tile_center_x = 622, tile_center_y = 631 WHERE tile_name LIKE 'Newfoundland';
UPDATE tiles SET tile_center_x = 1632, tile_center_y = 1522 WHERE tile_name LIKE 'Angola';
UPDATE tiles SET tile_center_x = 583, tile_center_y = 415 WHERE tile_name LIKE 'SZ 2 Labrador Sea';
UPDATE tiles SET tile_center_x = 3889, tile_center_y = 384 WHERE tile_name LIKE 'SZ 77 Bering Sea';
UPDATE tiles SET tile_center_x = 2401, tile_center_y = 893 WHERE tile_name LIKE 'Kashmir';
UPDATE tiles SET tile_center_x = 2056, tile_center_y = 490 WHERE tile_name LIKE 'Eastern Russia';
UPDATE tiles SET tile_center_x = 3187, tile_center_y = 1102 WHERE tile_name LIKE 'SZ 92 Philippine Sea';
UPDATE tiles SET tile_center_x = 3288, tile_center_y = 1031 WHERE tile_name LIKE 'Iwo Jima';
UPDATE tiles SET tile_center_x = 1713, tile_center_y = 672 WHERE tile_name LIKE 'Hungary-Romania';
UPDATE tiles SET tile_center_x = 2216, tile_center_y = 1790 WHERE tile_name LIKE 'SZ 65 Indian';
UPDATE tiles SET tile_center_x = 3363, tile_center_y = 1982 WHERE tile_name LIKE 'Tasmania';
UPDATE tiles SET tile_center_x = 2500, tile_center_y = 800 WHERE tile_name LIKE 'Western Sinkiang';
UPDATE tiles SET tile_center_x = 3039, tile_center_y = 1716 WHERE tile_name LIKE 'Western Australia';
UPDATE tiles SET tile_center_x = 2349, tile_center_y = 1502 WHERE tile_name LIKE 'SZ 61 Indian';
UPDATE tiles SET tile_center_x = 2375, tile_center_y = 752 WHERE tile_name LIKE 'Kyrgyz';
UPDATE tiles SET tile_center_x = 636, tile_center_y = 2126 WHERE tile_name LIKE 'SZ 52 South Atlantic';
UPDATE tiles SET tile_center_x = 1941, tile_center_y = 461 WHERE tile_name LIKE 'Moscow';
UPDATE tiles SET tile_center_x = 4577, tile_center_y = 947 WHERE tile_name LIKE 'SZ 91 East Pacific';
UPDATE tiles SET tile_center_x = 1253, tile_center_y = 305 WHERE tile_name LIKE 'SZ 9 North Atlantic';
UPDATE tiles SET tile_center_x = 4152, tile_center_y = 1092 WHERE tile_name LIKE 'Hawaiian Islands';
UPDATE tiles SET tile_center_x = 2714, tile_center_y = 834 WHERE tile_name LIKE 'Kansu';
UPDATE tiles SET tile_center_x = 3843, tile_center_y = 1465 WHERE tile_name LIKE 'SZ 100 Pacific';
UPDATE tiles SET tile_center_x = 1509, tile_center_y = 660 WHERE tile_name LIKE 'Switzerland';
UPDATE tiles SET tile_center_x = 2244, tile_center_y = 10 WHERE tile_name LIKE 'SZ 8 Kara Sea';
UPDATE tiles SET tile_center_x = 2586, tile_center_y = 927 WHERE tile_name LIKE 'Himalaya-Tibet';
UPDATE tiles SET tile_center_x = 1739, tile_center_y = 841 WHERE tile_name LIKE 'SZ 27 Aegean Sea';
UPDATE tiles SET tile_center_x = 1514, tile_center_y = 741 WHERE tile_name LIKE 'SZ 24 Tyrrhenian Sea';
UPDATE tiles SET tile_center_x = 423, tile_center_y = 1097 WHERE tile_name LIKE 'West Indies';
UPDATE tiles SET tile_center_x = 4212, tile_center_y = 1462 WHERE tile_name LIKE 'SZ 101 Pacific';
UPDATE tiles SET tile_center_x = 1760, tile_center_y = 283 WHERE tile_name LIKE 'Finland';
UPDATE tiles SET tile_center_x = 3077, tile_center_y = 1262 WHERE tile_name LIKE 'South Philippines';
UPDATE tiles SET tile_center_x = 3072, tile_center_y = 485 WHERE tile_name LIKE 'Amurskaya';
UPDATE tiles SET tile_center_x = 3962, tile_center_y = 648 WHERE tile_name LIKE 'SZ 82 North Pacific';
UPDATE tiles SET tile_center_x = 2253, tile_center_y = 443 WHERE tile_name LIKE 'Sverdlovsk';
UPDATE tiles SET tile_center_x = 2936, tile_center_y = 802 WHERE tile_name LIKE 'Shantung';
UPDATE tiles SET tile_center_x = 2022, tile_center_y = 1621 WHERE tile_name LIKE 'Madagascar';
UPDATE tiles SET tile_center_x = 1441, tile_center_y = 799 WHERE tile_name LIKE 'SZ 23 West Mediterranean';
UPDATE tiles SET tile_center_x = 4722, tile_center_y = 19 WHERE tile_name LIKE 'SZ 79 Arctic Ocean';
UPDATE tiles SET tile_center_x = 2235, tile_center_y = 1129 WHERE tile_name LIKE 'SZ 56 Persian Gulf';
UPDATE tiles SET tile_center_x = 4328, tile_center_y = 917 WHERE tile_name LIKE 'SZ 90 East Pacific';
UPDATE tiles SET tile_center_x = 2205, tile_center_y = 629 WHERE tile_name LIKE 'Kazakh';
UPDATE tiles SET tile_center_x = 2832, tile_center_y = 1180 WHERE tile_name LIKE 'French Indo-China';
UPDATE tiles SET tile_center_x = 1523, tile_center_y = 581 WHERE tile_name LIKE 'Western Germany';
UPDATE tiles SET tile_center_x = 1742, tile_center_y = 455 WHERE tile_name LIKE 'Baltic States';
UPDATE tiles SET tile_center_x = 2680, tile_center_y = 2133 WHERE tile_name LIKE 'SZ 69 Indian';
UPDATE tiles SET tile_center_x = 510, tile_center_y = 915 WHERE tile_name LIKE 'Bermuda';
UPDATE tiles SET tile_center_x = 2432, tile_center_y = 497 WHERE tile_name LIKE 'Omsk';
UPDATE tiles SET tile_center_x = 1895, tile_center_y = 1807 WHERE tile_name LIKE 'SZ 64 South West Indian';
UPDATE tiles SET tile_center_x = 3659, tile_center_y = 465 WHERE tile_name LIKE 'SZ 76 West Bering Sea';
UPDATE tiles SET tile_center_x = 3664, tile_center_y = 2024 WHERE tile_name LIKE 'New Zealand';
UPDATE tiles SET tile_center_x = 4259, tile_center_y = 540 WHERE tile_name LIKE 'SZ 83 Gulf of Alaska';
UPDATE tiles SET tile_center_x = 1457, tile_center_y = 1027 WHERE tile_name LIKE 'Sahara';
UPDATE tiles SET tile_center_x = 98, tile_center_y = 1589 WHERE tile_name LIKE 'SZ 41 Eastern Pacific';
UPDATE tiles SET tile_center_x = 1101, tile_center_y = 797 WHERE tile_name LIKE 'SZ 21 East Atlantic';
UPDATE tiles SET tile_center_x = 3482, tile_center_y = 1335 WHERE tile_name LIKE 'SZ 99 West Pacific';
UPDATE tiles SET tile_center_x = 2576, tile_center_y = 492 WHERE tile_name LIKE 'Novo-Sibirsk';
UPDATE tiles SET tile_center_x = 4768, tile_center_y = 1197 WHERE tile_name LIKE 'SZ 97 East Pacific';
UPDATE tiles SET tile_center_x = 77, tile_center_y = 736 WHERE tile_name LIKE 'Midwestern United States';
UPDATE tiles SET tile_center_x = 1319, tile_center_y = 829 WHERE tile_name LIKE 'Gibraltar';
UPDATE tiles SET tile_center_x = 1839, tile_center_y = 226 WHERE tile_name LIKE 'Karelija';
UPDATE tiles SET tile_center_x = 1202, tile_center_y = 1311 WHERE tile_name LIKE 'SZ 40 Mid Atlantic';
UPDATE tiles SET tile_center_x = 2677, tile_center_y = 1066 WHERE tile_name LIKE 'Burma';
UPDATE tiles SET tile_center_x = 1851, tile_center_y = 729 WHERE tile_name LIKE 'SZ 29 Black Sea';
UPDATE tiles SET tile_center_x = 3299, tile_center_y = 2151 WHERE tile_name LIKE 'SZ 70 Southern Ocean';
UPDATE tiles SET tile_center_x = 3076, tile_center_y = 649 WHERE tile_name LIKE 'Northern Manchukuo';
UPDATE tiles SET tile_center_x = 1836, tile_center_y = 624 WHERE tile_name LIKE 'Ukraine';
UPDATE tiles SET tile_center_x = 1797, tile_center_y = 999 WHERE tile_name LIKE 'Egypt';
UPDATE tiles SET tile_center_x = 139, tile_center_y = 891 WHERE tile_name LIKE 'Southern United States';
UPDATE tiles SET tile_center_x = 2130, tile_center_y = 909 WHERE tile_name LIKE 'Iran';
UPDATE tiles SET tile_center_x = 331, tile_center_y = 771 WHERE tile_name LIKE 'Northeastern United States';
UPDATE tiles SET tile_center_x = 2091, tile_center_y = 1310 WHERE tile_name LIKE 'SZ 55 Red Sea';
UPDATE tiles SET tile_center_x = 3082, tile_center_y = 922 WHERE tile_name LIKE 'SZ 73 East China Sea';
UPDATE tiles SET tile_center_x = 308, tile_center_y = 2049 WHERE tile_name LIKE 'SZ 47 Southeastern Pacific';
UPDATE tiles SET tile_center_x = 3021, tile_center_y = 1134 WHERE tile_name LIKE 'North Philippines';
UPDATE tiles SET tile_center_x = 1671, tile_center_y = 719 WHERE tile_name LIKE 'Balkans';
UPDATE tiles SET tile_center_x = 3192, tile_center_y = 1703 WHERE tile_name LIKE 'Central Australia';
UPDATE tiles SET tile_center_x = 2594, tile_center_y = 1335 WHERE tile_name LIKE 'SZ 59 Northeastern Indian';
UPDATE tiles SET tile_center_x = 4262, tile_center_y = 663 WHERE tile_name LIKE 'SZ 84 Northeastern Pacific';
UPDATE tiles SET tile_center_x = 344, tile_center_y = 1079 WHERE tile_name LIKE 'Cuba';
UPDATE tiles SET tile_center_x = 1364, tile_center_y = 1227 WHERE tile_name LIKE 'Guinean Coast';
UPDATE tiles SET tile_center_x = 4494, tile_center_y = 660 WHERE tile_name LIKE 'SZ 85 Northeast Pacific';
UPDATE tiles SET tile_center_x = 2024, tile_center_y = 1063 WHERE tile_name LIKE 'Arabian Peninsula';
UPDATE tiles SET tile_center_x = 1799, tile_center_y = 525 WHERE tile_name LIKE 'Belorussia';
UPDATE tiles SET tile_center_x = 3490, tile_center_y = 701 WHERE tile_name LIKE 'SZ 80 Northwest Pacific';
UPDATE tiles SET tile_center_x = 36, tile_center_y = 1091 WHERE tile_name LIKE 'Eastern Mexico';
UPDATE tiles SET tile_center_x = 225, tile_center_y = 1187 WHERE tile_name LIKE 'Central America';
UPDATE tiles SET tile_center_x = 3793, tile_center_y = 10 WHERE tile_name LIKE 'SZ 78 Arctic Ocean';
UPDATE tiles SET tile_center_x = 765, tile_center_y = 581 WHERE tile_name LIKE 'SZ 14 North Atlantic';
UPDATE tiles SET tile_center_x = 1020, tile_center_y = 311 WHERE tile_name LIKE 'SZ 4 Denmark Straight';
UPDATE tiles SET tile_center_x = 2848, tile_center_y = 897 WHERE tile_name LIKE 'Szechwan';
UPDATE tiles SET tile_center_x = 3363, tile_center_y = 1196 WHERE tile_name LIKE 'Guam';
UPDATE tiles SET tile_center_x = 3108, tile_center_y = 1007 WHERE tile_name LIKE 'Okinawa';
UPDATE tiles SET tile_center_x = 4665, tile_center_y = 1463 WHERE tile_name LIKE 'SZ 102 East Pacific';
UPDATE tiles SET tile_center_x = 3548, tile_center_y = 1869 WHERE tile_name LIKE 'SZ 105 Tasman Sea';
UPDATE tiles SET tile_center_x = 1545, tile_center_y = 700 WHERE tile_name LIKE 'Italy';
UPDATE tiles SET tile_center_x = 1816, tile_center_y = 429 WHERE tile_name LIKE 'Novgorod';
UPDATE tiles SET tile_center_x = 1442, tile_center_y = 701 WHERE tile_name LIKE 'Vichy France';
UPDATE tiles SET tile_center_x = 1330, tile_center_y = 902 WHERE tile_name LIKE 'Morocco';
UPDATE tiles SET tile_center_x = 1608, tile_center_y = 625 WHERE tile_name LIKE 'Austria-Czechoslovakia';
UPDATE tiles SET tile_center_x = 2086, tile_center_y = 1463 WHERE tile_name LIKE 'SZ 60 Western Indian';
UPDATE tiles SET tile_center_x = 1519, tile_center_y = 782 WHERE tile_name LIKE 'Sardinia';
UPDATE tiles SET tile_center_x = 992, tile_center_y = 574 WHERE tile_name LIKE 'SZ 15 North Atlantic';
UPDATE tiles SET tile_center_x = 2139, tile_center_y = 6 WHERE tile_name LIKE 'Novaya-Zemlya';
UPDATE tiles SET tile_center_x = 1220, tile_center_y = 46 WHERE tile_name LIKE 'SZ 5 Greenland Sea';
UPDATE tiles SET tile_center_x = 394, tile_center_y = 559 WHERE tile_name LIKE 'Eastern Canada';
UPDATE tiles SET tile_center_x = 1375, tile_center_y = 535 WHERE tile_name LIKE 'England';
UPDATE tiles SET tile_center_x = 3392, tile_center_y = 475 WHERE tile_name LIKE 'SZ 75 Sea of Okhotsk';
UPDATE tiles SET tile_center_x = 958, tile_center_y = 1470 WHERE tile_name LIKE 'SZ 43 Mid Atlantic';
UPDATE tiles SET tile_center_x = 822, tile_center_y = 59 WHERE tile_name LIKE 'Greenland';
UPDATE tiles SET tile_center_x = 4703, tile_center_y = 2198 WHERE tile_name LIKE 'SZ 109 South Pacific';
UPDATE tiles SET tile_center_x = 678, tile_center_y = 1415 WHERE tile_name LIKE 'Northern Brazil';
UPDATE tiles SET tile_center_x = 1579, tile_center_y = 495 WHERE tile_name LIKE 'SZ 11 West Baltic Sea';
UPDATE tiles SET tile_center_x = 352, tile_center_y = 953 WHERE tile_name LIKE 'SZ 31 West Atlantic';
UPDATE tiles SET tile_center_x = 3347, tile_center_y = 1832 WHERE tile_name LIKE 'New South Wales';
UPDATE tiles SET tile_center_x = 2839, tile_center_y = 782 WHERE tile_name LIKE 'Inner Mongolia';
UPDATE tiles SET tile_center_x = 314, tile_center_y = 1647 WHERE tile_name LIKE 'SZ 42 Eastern Pacific';
UPDATE tiles SET tile_center_x = 2294, tile_center_y = 975 WHERE tile_name LIKE 'Baluchistan';
UPDATE tiles SET tile_center_x = 958, tile_center_y = 2144 WHERE tile_name LIKE 'SZ 53 South Atlantic';
UPDATE tiles SET tile_center_x = 1593, tile_center_y = 829 WHERE tile_name LIKE 'Sicily';
UPDATE tiles SET tile_center_x = 1977, tile_center_y = 899 WHERE tile_name LIKE 'Iraq';
UPDATE tiles SET tile_center_x = 1322, tile_center_y = 1085 WHERE tile_name LIKE 'French West Africa';
UPDATE tiles SET tile_center_x = 3336, tile_center_y = 1687 WHERE tile_name LIKE 'Queensland';
UPDATE tiles SET tile_center_x = 1940, tile_center_y = 590 WHERE tile_name LIKE 'Southern Russia';
UPDATE tiles SET tile_center_x = 3719, tile_center_y = 665 WHERE tile_name LIKE 'SZ 81 North Pacific';
UPDATE tiles SET tile_center_x = 3317, tile_center_y = 591 WHERE tile_name LIKE 'Sakhalin Island';
UPDATE tiles SET tile_center_x = 1716, tile_center_y = 1394 WHERE tile_name LIKE 'Belgian Congo';
UPDATE tiles SET tile_center_x = 2002, tile_center_y = 724 WHERE tile_name LIKE 'Caucasus';
UPDATE tiles SET tile_center_x = 3487, tile_center_y = 1114 WHERE tile_name LIKE 'SZ 93 West Pacific';
UPDATE tiles SET tile_center_x = 3106, tile_center_y = 295 WHERE tile_name LIKE 'Yakutsk';
UPDATE tiles SET tile_center_x = 1352, tile_center_y = 771 WHERE tile_name LIKE 'Spain';
UPDATE tiles SET tile_center_x = 2273, tile_center_y = 892 WHERE tile_name LIKE 'Afghanistan';
UPDATE tiles SET tile_center_x = 3823, tile_center_y = 1146 WHERE tile_name LIKE 'SZ 94 Pacific';
UPDATE tiles SET tile_center_x = 453, tile_center_y = 799 WHERE tile_name LIKE 'SZ 18 West Atlantic';
UPDATE tiles SET tile_center_x = 1444, tile_center_y = 1782 WHERE tile_name LIKE 'SZ 50 South Atlantic';
UPDATE tiles SET tile_center_x = 1194, tile_center_y = 593 WHERE tile_name LIKE 'SZ 16 North Atlantic';
UPDATE tiles SET tile_center_x = 1610, tile_center_y = 734 WHERE tile_name LIKE 'SZ 25 Adriatic Sea';
UPDATE tiles SET tile_center_x = 3306, tile_center_y = 114 WHERE tile_name LIKE 'Eastern Siberia';
UPDATE tiles SET tile_center_x = 3599, tile_center_y = 205 WHERE tile_name LIKE 'Kamchatka';
UPDATE tiles SET tile_center_x = 1906, tile_center_y = 1553 WHERE tile_name LIKE 'Mozambique';
UPDATE tiles SET tile_center_x = 1957, tile_center_y = 1247 WHERE tile_name LIKE 'Ethiopia';
UPDATE tiles SET tile_center_x = 1289, tile_center_y = 536 WHERE tile_name LIKE 'Ireland';
UPDATE tiles SET tile_center_x = 1829, tile_center_y = 808 WHERE tile_name LIKE 'Western Turkey';
UPDATE tiles SET tile_center_x = 1689, tile_center_y = 786 WHERE tile_name LIKE 'Macedonia';
UPDATE tiles SET tile_center_x = 2888, tile_center_y = 1011 WHERE tile_name LIKE 'Kwangtung';
UPDATE tiles SET tile_center_x = 2932, tile_center_y = 1351 WHERE tile_name LIKE 'Borneo';
UPDATE tiles SET tile_center_x = 1069, tile_center_y = 1147 WHERE tile_name LIKE 'Cape Verde Islands';
UPDATE tiles SET tile_center_x = 2942, tile_center_y = 333 WHERE tile_name LIKE 'Southeastern Siberia';
UPDATE tiles SET tile_center_x = 2025, tile_center_y = 616 WHERE tile_name LIKE 'Stalingrad';
UPDATE tiles SET tile_center_x = 4480, tile_center_y = 1196 WHERE tile_name LIKE 'SZ 96 Pacific';
UPDATE tiles SET tile_center_x = 2888, tile_center_y = 1461 WHERE tile_name LIKE 'Java';
UPDATE tiles SET tile_center_x = 4105, tile_center_y = 913 WHERE tile_name LIKE 'SZ 89 Pacific';
UPDATE tiles SET tile_center_x = 3145, tile_center_y = 1306 WHERE tile_name LIKE 'SZ 98 Philippine Sea';
UPDATE tiles SET tile_center_x = 1516, tile_center_y = 331 WHERE tile_name LIKE 'Norway';
UPDATE tiles SET tile_center_x = 936, tile_center_y = 1252 WHERE tile_name LIKE 'SZ 39 Mid Atlantic';
UPDATE tiles SET tile_center_x = 424, tile_center_y = 144 WHERE tile_name LIKE 'Baffin Island';
UPDATE tiles SET tile_center_x = 1818, tile_center_y = 891 WHERE tile_name LIKE 'SZ 28 Eastern Mediterranean';
UPDATE tiles SET tile_center_x = 2604, tile_center_y = 720 WHERE tile_name LIKE 'Eastern Sinkiang';
UPDATE tiles SET tile_center_x = 2004, tile_center_y = 41 WHERE tile_name LIKE 'SZ 7 Barents Sea';
UPDATE tiles SET tile_center_x = 1204, tile_center_y = 1476 WHERE tile_name LIKE 'SZ 44 Mid Atlantic';
UPDATE tiles SET tile_center_x = 3246, tile_center_y = 852 WHERE tile_name LIKE 'Southern Japan';
UPDATE tiles SET tile_center_x = 1703, tile_center_y = 1712 WHERE tile_name LIKE 'Southern Africa';
UPDATE tiles SET tile_center_x = 1942, tile_center_y = 799 WHERE tile_name LIKE 'Eastern Turkey';
UPDATE tiles SET tile_center_x = 1017, tile_center_y = 807 WHERE tile_name LIKE 'Azores';
UPDATE tiles SET tile_center_x = 2667, tile_center_y = 1572 WHERE tile_name LIKE 'SZ 62 Indian';
UPDATE tiles SET tile_center_x = 222, tile_center_y = 323 WHERE tile_name LIKE 'SZ 1 Hudson Bay';
UPDATE tiles SET tile_center_x = 4590, tile_center_y = 1821 WHERE tile_name LIKE 'SZ 107 South Pacific';
UPDATE tiles SET tile_center_x = 1456, tile_center_y = 2167 WHERE tile_name LIKE 'SZ 54 South Atlantic';
UPDATE tiles SET tile_center_x = 2754, tile_center_y = 1156 WHERE tile_name LIKE 'Thai-Malay';
UPDATE tiles SET tile_center_x = 3941, tile_center_y = 2189 WHERE tile_name LIKE 'SZ 108 South Pacific';
UPDATE tiles SET tile_center_x = 1069, tile_center_y = 1762 WHERE tile_name LIKE 'SZ 49 South Atlantic';
UPDATE tiles SET tile_center_x = 2414, tile_center_y = 1112 WHERE tile_name LIKE 'Bombay';
UPDATE tiles SET tile_center_x = 3939, tile_center_y = 1805 WHERE tile_name LIKE 'SZ 106 Southwest Pacific';
UPDATE tiles SET tile_center_x = 3922, tile_center_y = 874 WHERE tile_name LIKE 'SZ 88 Pacific';
UPDATE tiles SET tile_center_x = 461, tile_center_y = 1569 WHERE tile_name LIKE 'Western South America';
UPDATE tiles SET tile_center_x = 1136, tile_center_y = 229 WHERE tile_name LIKE 'Iceland';
UPDATE tiles SET tile_center_x = 976, tile_center_y = 1044 WHERE tile_name LIKE 'SZ 34 Atlantic';
UPDATE tiles SET tile_center_x = 1628, tile_center_y = 1246 WHERE tile_name LIKE 'French Equatorial Africa';
UPDATE tiles SET tile_center_x = 3854, tile_center_y = 974 WHERE tile_name LIKE 'Midway Island';
UPDATE tiles SET tile_center_x = 1289, tile_center_y = 790 WHERE tile_name LIKE 'Portugal';
UPDATE tiles SET tile_center_x = 3780, tile_center_y = 1601 WHERE tile_name LIKE 'Fiji';
UPDATE tiles SET tile_center_x = 4167, tile_center_y = 1194 WHERE tile_name LIKE 'SZ 95 Pacific';
UPDATE tiles SET tile_center_x = 3495, tile_center_y = 1463 WHERE tile_name LIKE 'Solomon Islands';
UPDATE tiles SET tile_center_x = 2967, tile_center_y = 1542 WHERE tile_name LIKE 'SZ 63 Timor Sea';
UPDATE tiles SET tile_center_x = 3198, tile_center_y = 1474 WHERE tile_name LIKE 'SZ 103 Arafura Sea';
UPDATE tiles SET tile_center_x = 775, tile_center_y = 1048 WHERE tile_name LIKE 'SZ 33 Atlantic';
UPDATE tiles SET tile_center_x = 536, tile_center_y = 1044 WHERE tile_name LIKE 'SZ 32 Atlantic';
UPDATE tiles SET tile_center_x = 1213, tile_center_y = 1019 WHERE tile_name LIKE 'Rio de Oro';
UPDATE tiles SET tile_center_x = 631, tile_center_y = 813 WHERE tile_name LIKE 'SZ 19 Atlantic';
UPDATE tiles SET tile_center_x = 2207, tile_center_y = 770 WHERE tile_name LIKE 'Uzbek';
UPDATE tiles SET tile_center_x = 1442, tile_center_y = 514 WHERE tile_name LIKE 'SZ 17 English Channel';
UPDATE tiles SET tile_center_x = 2446, tile_center_y = 237 WHERE tile_name LIKE 'Western Siberia';
UPDATE tiles SET tile_center_x = 1870, tile_center_y = 1397 WHERE tile_name LIKE 'Kenya-Tanganyika';
UPDATE tiles SET tile_center_x = 3641, tile_center_y = 904 WHERE tile_name LIKE 'SZ 87 West Pacific';
UPDATE tiles SET tile_center_x = 2831, tile_center_y = 1805 WHERE tile_name LIKE 'SZ 67 South East Indian';
UPDATE tiles SET tile_center_x = 1774, tile_center_y = 1565 WHERE tile_name LIKE 'Rhodesia';
UPDATE tiles SET tile_center_x = 1468, tile_center_y = 912 WHERE tile_name LIKE 'Algeria';
UPDATE tiles SET tile_center_x = 504, tile_center_y = 1822 WHERE tile_name LIKE 'Southern South America';
UPDATE tiles SET tile_center_x = 1850, tile_center_y = 469 WHERE tile_name LIKE 'Western Russia';
UPDATE tiles SET tile_center_x = 1798, tile_center_y = 1163 WHERE tile_name LIKE 'Anglo-Egyptian Sudan';
UPDATE tiles SET tile_center_x = 3888, tile_center_y = 554 WHERE tile_name LIKE 'Eastern Aleutian Islands';
UPDATE tiles SET tile_center_x = 3671, tile_center_y = 1230 WHERE tile_name LIKE 'Marshall Islands';
UPDATE tiles SET tile_center_x = 2551, tile_center_y = 1809 WHERE tile_name LIKE 'SZ 66 Indian';
UPDATE tiles SET tile_center_x = 3308, tile_center_y = 728 WHERE tile_name LIKE 'Northern Japan';
UPDATE tiles SET tile_center_x = 2926, tile_center_y = 1165 WHERE tile_name LIKE 'SZ 72 South China Sea';
UPDATE tiles SET tile_center_x = 1672, tile_center_y = 556 WHERE tile_name LIKE 'Western Poland';
UPDATE tiles SET tile_center_x = 1623, tile_center_y = 254 WHERE tile_name LIKE 'Sweden';
UPDATE tiles SET tile_center_x = 2877, tile_center_y = 62 WHERE tile_name LIKE 'Siberia';
UPDATE tiles SET tile_center_x = 2789, tile_center_y = 350 WHERE tile_name LIKE 'Southern Siberia';
UPDATE tiles SET tile_center_x = 1640, tile_center_y = 993 WHERE tile_name LIKE 'Libya';
UPDATE tiles SET tile_center_x = 2773, tile_center_y = 655 WHERE tile_name LIKE 'Mongolia';
UPDATE tiles SET tile_center_x = 147, tile_center_y = 1006 WHERE tile_name LIKE 'SZ 30 Gulf of Mexico';
UPDATE tiles SET tile_center_x = 113, tile_center_y = 2055 WHERE tile_name LIKE 'SZ 46 Southeastern Pacific';
UPDATE tiles SET tile_center_x = 1124, tile_center_y = 1043 WHERE tile_name LIKE 'SZ 35 East Atlantic';
UPDATE tiles SET tile_center_x = 3721, tile_center_y = 551 WHERE tile_name LIKE 'Western Aleutian Islands';
UPDATE tiles SET tile_center_x = 1918, tile_center_y = 868 WHERE tile_name LIKE 'Syria';
UPDATE tiles SET tile_center_x = 1586, tile_center_y = 553 WHERE tile_name LIKE 'Eastern Germany';
UPDATE tiles SET tile_center_x = 2291, tile_center_y = 1265 WHERE tile_name LIKE 'SZ 57 Arabian Sea';
UPDATE tiles SET tile_center_x = 3635, tile_center_y = 1099 WHERE tile_name LIKE 'Wake';
UPDATE tiles SET tile_center_x = 3285, tile_center_y = 1436 WHERE tile_name LIKE 'New Guinea';
UPDATE tiles SET tile_center_x = 2553, tile_center_y = 1045 WHERE tile_name LIKE 'Calcutta';
UPDATE tiles SET tile_center_x = 2649, tile_center_y = 320 WHERE tile_name LIKE 'Southwestern Siberia';
UPDATE tiles SET tile_center_x = 710, tile_center_y = 1610 WHERE tile_name LIKE 'Southern Brazil';
UPDATE tiles SET tile_center_x = 815, tile_center_y = 1788 WHERE tile_name LIKE 'SZ 48 South Atlantic';
UPDATE tiles SET tile_center_x = 1831, tile_center_y = 351 WHERE tile_name LIKE 'Leningrad';
UPDATE tiles SET tile_center_x = 1488, tile_center_y = 52 WHERE tile_name LIKE 'SZ 6 Norwegian Sea';
UPDATE tiles SET tile_center_x = 4835, tile_center_y = 1013 WHERE tile_name LIKE 'Western Mexico';
UPDATE tiles SET tile_center_x = 4658, tile_center_y = 437 WHERE tile_name LIKE 'Western Canada';
UPDATE tiles SET tile_center_x = 3228, tile_center_y = 581 WHERE tile_name LIKE 'Vladivostok';
UPDATE tiles SET tile_center_x = 302, tile_center_y = 1131 WHERE tile_name LIKE 'SZ 37 Caribbean Sea';
UPDATE tiles SET tile_center_x = 4744, tile_center_y = 687 WHERE tile_name LIKE 'Northwestern United States';
UPDATE tiles SET tile_center_x = 3582, tile_center_y = 1615 WHERE tile_name LIKE 'SZ 104 Coral Sea';
UPDATE tiles SET tile_center_x = 2820, tile_center_y = 1298 WHERE tile_name LIKE 'SZ 71 South China Sea';
UPDATE tiles SET tile_center_x = 2741, tile_center_y = 487 WHERE tile_name LIKE 'Irkutsk';
UPDATE tiles SET tile_center_x = 3012, tile_center_y = 1392 WHERE tile_name LIKE 'Celebes';
UPDATE tiles SET tile_center_x = 2479, tile_center_y = 1263 WHERE tile_name LIKE 'Ceylon';
UPDATE tiles SET tile_center_x = 405, tile_center_y = 1299 WHERE tile_name LIKE 'Northern South America';
UPDATE tiles SET tile_center_x = 1742, tile_center_y = 533 WHERE tile_name LIKE 'Eastern Poland';
UPDATE tiles SET tile_center_x = 2601, tile_center_y = 1163 WHERE tile_name LIKE 'SZ 58 Bay of Bengal';